spring.application.name: resource001

server:
  port: 8070

management.security.enabled: false
        
security:
  oauth2:
    client:
      clientId: openIdDemo
      clientSecret: a5396a8c-d074-4768-a7b3-f95e6d310f20
      accessTokenUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/auth
    resource:
      userInfoUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/userinfo        
    #added for Entitlements API
    entitlements:
      entitlementsUri: http://localhost:8080/auth/realms/demo/authz/entitlement/openIdDemo      
    #added for UMA
    uma:
      permissionUri: http://localhost:8080/auth/realms/demo/authz/protection/permission
      authorizeUri: http://localhost:8080/auth/realms/demo/authz/authorize
        
logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO